(() => {
 const c=window.hcaSupabase; if(!c)return; const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'); const num=v=>Number.isFinite(Number(v))?Number(v):0; const clean=v=>window.hcaDisplayTeamName(v||'');
 let games=[],teams=[];
 const seasonNum=s=>Number(String(s||'').match(/\d+/)?.[0]||0);
 async function load(){
  const [{data:g,error:ge},{data:t,error:te}]=await Promise.all([c.from('games').select('id,season,week,game_date,home_team_id,away_team_id,home_team_name,away_team_name,home_score,away_score,status,overtime'),c.from('teams').select('id,name,logo').order('name')]);
  if(ge)throw ge;if(te)throw te;games=g||[];teams=t||[];
  const ss=[...new Set(games.map(x=>x.season).filter(Boolean))].sort((a,b)=>seasonNum(b)-seasonNum(a));const sel=document.getElementById('games-season');sel.innerHTML='<option value="all">ALL SEASONS</option>'+ss.map(s=>`<option>${esc(s)}</option>`).join('');
  const ts=teams;document.getElementById('games-team').innerHTML='<option value="all">ALL TEAMS</option>'+ts.map(t=>`<option value="${esc(t.id)}">${esc(clean(t.name))}</option>`).join('');render();
 }
 function render(){const season=document.getElementById('games-season').value,team=document.getElementById('games-team').value;const rows=games.filter(g=>(season==='all'||g.season===season)&&(team==='all'||String(g.home_team_id)===team||String(g.away_team_id)===team)).sort((a,b)=>seasonNum(b.season)-seasonNum(a.season)||num(b.week)-num(a.week));document.getElementById('games-count').textContent=`SHOWING ${rows.length} OF ${games.length} GAMES`;const el=document.getElementById('games-list');if(!rows.length){el.innerHTML='<div class="games-empty">NO GAMES FOUND.</div>';return;}el.innerHTML=rows.map(g=>{const h=teams.find(t=>String(t.id)===String(g.home_team_id)),a=teams.find(t=>String(t.id)===String(g.away_team_id));const hs=num(g.home_score),as=num(g.away_score),final=String(g.status||'').toLowerCase()!=='scheduled'&&Number.isFinite(Number(g.home_score));const label=final?(g.overtime?'FINAL · OT':'FINAL'):'SCHEDULED';return `<a class="league-game-row" href="game.html?id=${encodeURIComponent(g.id)}"><div class="league-game-week">${esc(g.season||'—')}<br>WEEK ${esc(g.week??'—')}</div><div class="league-game-matchup"><div class="league-game-team"><img src="${esc(h?.logo||'')}" alt="">${esc(clean(g.home_team_name||h?.name))}</div><div class="league-game-score">${final?`${hs} — ${as}`:'VS'}</div><div class="league-game-team"><img src="${esc(a?.logo||'')}" alt="">${esc(clean(g.away_team_name||a?.name))}</div></div><div class="league-game-meta"><b>${label}</b>${g.game_date?esc(new Date(g.game_date).toLocaleDateString()):'HCA GAMECAST'} →</div></a>`}).join('')}
 document.addEventListener('change',e=>{if(e.target.id==='games-season'||e.target.id==='games-team')render()});load().catch(e=>{document.getElementById('games-list').innerHTML=`<div class="games-empty">Could not load games: ${esc(e.message)}</div>`});
})();
